version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db

  db:
    image: "mongo"
    restart: always
    ports:
      - "5432:27017"
    env_file:
      - .env
    volumes: 
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb
      - ./scripts/mongo/seed/:/home/mongodb/seed
      - ./data/db:/data/db
