version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://appUser:Pwd12345%21@db:27017/viter?serverSelectionTimeoutMS=50000&connectTimeoutMS=10000&authSource=viter&authMechanism=SCRAM-SHA-256
    depends_on:
      - db
    networks:
      - docker_network

  db:
    image: "mongo"
    restart: always
    ports:
      - "5432:27017"
    env_file:
      - .env
    volumes: 
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb
      - ./scripts/mongo/seed/:/home/mongodb/seed
      - ./data/db:/data/db
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
    