version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db

  db:
    env_file:
      - .env
    image: "mongo"
    restart: always
    ports:
      - "5432:27017"
    volumes: 
      - ./data/db:/data/db

  mongo-seed:
    build: ./data/mock
    env_file:
      - .env
    links:
      - db
