apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    viter.service: api
  name: api
spec:
  replicas: 4
  selector:
    matchLabels:
      viter.service: api
  strategy: {}
  template:
    metadata:
      labels:
        viter.network/apinetwork: "true"
        viter.service: api
    spec:
      containers:
        - env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: env
            - name: TOKEN_KEY
              valueFrom:
                configMapKeyRef:
                  key: TOKEN_KEY
                  name: env
          image: luispereirav/scc:latest
          name: api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
