apiVersion: v1
kind: Service
metadata:
  labels:
    viter.service: db
  name: db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 27017
  selector:
    viter.service: db
status:
  loadBalancer: {}
